version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bugs
    hostname: bugs
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "8080:15672"